### ISSUE TITLE
add success button

### ISSUE THREAD

**Issue by bhimeshagrawal** [anurag-crypto/Awesome-web-components#3]

**Comment by prajwalpoojary** [comment]
Can you assign this to me?

**Comment by shryy** [comment]
Hi, I've completed this issue. Please have a look at it here:
Pull request: https://github.com/anurag-crypto/Awesome-web-components/pull/6

- [x] HTML structuring
- [x] CSS Styling

Final result: 
![image](https://user-images.githubusercontent.com/91775991/135708149-3b3cba02-8a7f-4e6a-93fe-ad9eec0e91d0.png)

**Comment by Hussain6** [comment]
I have added the success button and applied hover functionality to both buttons.
You can have a look

![image](https://user-images.githubusercontent.com/63571816/135708785-c4fe3b05-7098-43c8-8ae4-dfa6b4ebf15f.png)
